version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    container_name: app
    entrypoint: wait-for postgres:5432 -t 40 -- sh -c "npm install && npx prisma migrate dev && npm run start:dev"
    restart: always
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - .env

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    env_file:
      - .env

  control-center:
    container_name: control_center
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - 9021:9021
    env_file:
      - .env

volumes:
  postgres:
